# Generated by Django 5.2.8 on 2025-11-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='nome',
            new_name='name',
        ),
    ]
