# Generated by Django 5.2.8 on 2025-11-26 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='pensamento_gerado_em',
            new_name='thought_generated_at',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='pensamento_do_dia',
            new_name='thought_of_the_day',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='especie',
        ),
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('horse', 'Horse'), ('other', 'Other')], default='other', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
